name: SkillManager
main: SkillManager\SkillManager
author: TeleMC
version: 1.0.0
api:
  - 3.2.0
  - 3.3.0
  - 4.0.0
commands:
  스킬:
    description: 스킬 관련 명령어입니다.
  소리:
    description: 소리 테스트
